apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-long
  labels:
    app: so-long
spec:
  replicas: 1
  selector:
    matchLabels:
      app: so-long
  template:
    metadata:
      labels:
        app: so-long
    spec:
      containers:
        - name: so-long
          image: llecout/so_long:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: so-long
spec:
  type: ClusterIP
  selector:
    app: so-long
  ports:
    - port: 8888
      targetPort: 8888
